name: pawWatch
options:
  bundleIdPrefix: com.stonezone
  deploymentTarget:
    iOS: "18.4"
    watchOS: "11.0"
  developmentLanguage: en
  xcodeVersion: "16.3"

settings:
  base:
    SWIFT_VERSION: "6.2"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  pawWatchFeature:
    path: pawWatchPackage

targets:
  pawWatch:
    type: application
    platform: iOS
    deploymentTarget: "18.4"
    sources:
      - pawWatch
    dependencies:
      - package: pawWatchFeature
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.pawWatch
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES

  pawWatch Watch App:
    type: application
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: pawWatch Watch App
    dependencies:
      - package: pawWatchFeature
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.pawWatch.watchkitapp
        PRODUCT_NAME: pawWatch Watch App
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: pawWatch Watch App/Info.plist
        CODE_SIGN_ENTITLEMENTS: Config/pawWatch_Watch_App.entitlements
        SWIFT_VERSION: "6.2"
        ENABLE_PREVIEWS: YES
        TARGETED_DEVICE_FAMILY: 4
        SKIP_INSTALL: NO
        WATCHOS_DEPLOYMENT_TARGET: "11.0"
        SUPPORTS_MACCATALYST: NO
        COPY_PHASE_STRIP: NO
