name: pawWatch
options:
  bundleIdPrefix: com.stonezone
  deploymentTarget:
    iOS: "18.4"
    watchOS: "11.0"
  developmentLanguage: en
  xcodeVersion: "16.3"

settings:
  base:
    SWIFT_VERSION: "6.2"
    MARKETING_VERSION: "1.0.60"
    CURRENT_PROJECT_VERSION: "60"
    DEVELOPMENT_TEAM: 78725QX6PZ

packages:
  pawWatchFeature:
    path: pawWatchPackage

targets:
  pawWatch:
    type: application
    platform: iOS
    deploymentTarget: "18.4"
    sources:
      - path: pawWatch
      - path: Sources/LiveActivity
    dependencies:
      - package: pawWatchFeature
      - target: "pawWatch Watch App"
        embed: true
      - target: pawWatchWidgetExtension
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.pawWatch
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      configurations:
        Release:
          CODE_SIGN_ENTITLEMENTS: Config/pawWatch.entitlements

  pawWatch Watch App:
    type: application
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: "pawWatch Watch App"
    dependencies:
      - package: pawWatchFeature
      - target: pawWatchWatchWidget
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.pawWatch.watchkitapp
        PRODUCT_NAME: pawWatch Watch App
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: pawWatch Watch App/Info.plist
        INFOPLIST_KEY_WKApplication: YES
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.stonezone.pawWatch
        CODE_SIGN_ENTITLEMENTS: Config/pawWatch_Watch_App.entitlements
        SWIFT_VERSION: "6.2"
        ENABLE_PREVIEWS: YES
        TARGETED_DEVICE_FAMILY: 4
        SKIP_INSTALL: YES
        WATCHOS_DEPLOYMENT_TARGET: "11.0"
        SUPPORTS_MACCATALYST: NO
        COPY_PHASE_STRIP: NO

  pawWatchWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "18.4"
    sources:
      - path: pawWatchWidgetExtension
      - path: Sources/LiveActivity
    dependencies:
      - package: pawWatchFeature
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.pawWatch.widget
        INFOPLIST_FILE: pawWatchWidgetExtension/Info.plist
        APPLICATION_EXTENSION_API_ONLY: YES
        SWIFT_VERSION: "6.2"
      configurations:
        Release:
          CODE_SIGN_ENTITLEMENTS: Config/pawWatchWidgetExtension.entitlements

  pawWatchWatchWidget:
    type: app-extension
    platform: watchOS
    deploymentTarget: "11.0"
    sources:
      - path: pawWatchWatchWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.pawWatch.watchkitapp.widget
        INFOPLIST_FILE: pawWatchWatchWidget/Info.plist
        APPLICATION_EXTENSION_API_ONLY: YES
        SWIFT_VERSION: "6.2"
    dependencies:
      - package: pawWatchFeature

schemes:
  pawWatch:
    build:
      targets:
        pawWatch: [run, archive, profile, analyze, test]
        "pawWatch Watch App": [run, archive, profile, analyze]
    run:
      config: Debug
  pawWatch Watch App:
    build:
      targets:
        "pawWatch Watch App": [run, archive, profile, analyze]
    run:
      config: Debug
